name: Scheduled Deploy

on:
  schedule:
    - cron: '0 10 9 10 *' # JST 19:00 = UTC 10:00, 2025年10月9日
  workflow_dispatch: # 手動実行も可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
      - name: Push to release branch
        run: |
          git checkout -B release
          git push origin release --force